[model]
endpoint="hf"
# IN FUTURE UPDATES: can be "hf" (huggingface) | "openai" | etc etc
repo_id="Qwen/Qwen2.5-Coder-32B-Instruct" # NORMAL VALUE
#repo_id="Qwen/Qwen3-4B-Instruct-2507" # TEST VALUE
provider="nscale"

[quiz]
num_questions=2 # in the config rather than changeable within the app just to keep an eye on credit usage